In [1]:
import pandas as pd
import numpy as np
import csv

¿Qué diferencia hay entre una Serie y un DataFrame?
 DAtaframe es bidimensional y serie unidimensional


Es el turno de los DataFrames

In [6]:
#Crea un array de dos dimensiones con 4 filas y 3 columnas.
a_1= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [8]:
a_1.shape

(4, 3)

In [22]:
#Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
df = pd.DataFrame(a_1, columns=["España", "Francia", "Italia"]) # convertir primero en df e indicarle como quiero que se llamen las columnas 
df.head()

     España Francia  Italia
0  francnia  Italia  España
1         4       5       6
2         7       8       9
3        10      11      12

In [24]:
#Descarga el archivo "medallas" y carga el DataFrame.

df_medallas = pd.read_csv("files/medallas (1).csv")
df_medallas.head()

   Unnamed: 0           País   Oro  Plata  Bronce
0           1          China  1473    994     720
1           2          Japón  1032   1037     985
2           3  Corea del Sur   745    663     827
3           4           Irán   179    181     197
4           5     Kazajistán   155    158     224

In [26]:
##Usando el loc extrae todas las columnas de la fila de Tailandia.
df_medallas.loc[df_medallas,["País"]=="Tailandia"]

   Unnamed: 0       País  Oro  Plata  Bronce
6           7  Tailandia  132    175     278

In [33]:
#Usando el loc extrae todas las columnas de China e Irán.
df_medallas.loc[(df_medallas["País"] == "China") | (df_medallas["País"] == "Irán")]

   Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

In [34]:
df_medallas[df_medallas["País"].isin(["China", "Irán"])]

   Unnamed: 0   País   Oro  Plata  Bronce
0           1  China  1473    994     720
3           4   Irán   179    181     197

In [48]:

#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

df_medallas.loc[["China", "Irán"], ["Oro", "Plata", "Bronce"]]

        Oro  Plata  Bronce
País
China  1473    994     720
Irán    179    181     197

In [64]:

#Usando el iloc extrae la información de la India. Devolved todas las columnas.
df_medallas.iloc[5,:]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [55]:
df_medallas

                 Unnamed: 0   Oro  Plata  Bronce
País
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [71]:

#Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
df_medallas.iloc[0:3]

               Unnamed: 0   Oro  Plata  Bronce
País
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [ ]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [ ]:
#Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

3-Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [ ]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [ ]:
# A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.

In [ ]:
# Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

In [ ]:
# Extrae el valor para el índice "lunes"

In [ ]:

#Extrae el valor para el índice "lunes", "martes" y "miércoles"

In [ ]:

#Extrae el valor para el índice "lunes" y "domingo".