In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

# Librerías de visualización
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("files/world_data_full_apply.csv", index_col = 0)
df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.230,323.0,32.49,93.0,Kabul,8.672,149.90,2.3,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.7,47.9,Kabul,64.5,638.0,0.43,Pashto,78.4,0.28,NaN,48.9,9.3,71.4,11.12,NaN,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.748,9.0,11.78,355.0,Tirana,4.536,119.05,1.4,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.0,7.8,Tirana,78.5,15.0,1.12,Albanian,56.9,1.20,NaN,55.7,18.6,36.6,12.33,NaN,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,NaN,317.0,24.28,213.0,Algiers,150.006,151.36,2.0,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.4,20.1,Algiers,76.7,112.0,0.95,Arabic,28.1,1.72,NaN,41.2,37.2,66.1,11.70,NaN,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.000,NaN,7.20,376.0,Andorra la Vella,469.000,NaN,NaN,EUR,1.27,34.0,1.51,3.154058e+09,106.4,NaN,2.7,Andorra la Vella,NaN,NaN,6.63,Catalan,36.4,3.33,77.142,NaN,NaN,NaN,NaN,67.873,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,NaN,117.0,40.73,244.0,Luanda,34.693,261.73,17.1,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.3,51.6,Luanda,60.8,241.0,0.71,Portuguese,33.4,0.21,NaN,77.5,9.2,49.1,6.89,NaN,-11.202692,17.873887,Africa

In [5]:
#Identificación de Valores Nulos: Identifica todas las columnas que contienen valores nulos en el DataFrame.
df.columns[df.isnull().any()]

Index(['abbreviation', 'agricultural_land', 'land_area', 'armed_forces_size',
       'birth_rate', 'calling_code', 'capital/major_city', 'co2-emissions',
       'cpi', 'cpi_change', 'currency-code', 'fertility_rate', 'forested_area',
       'gasoline_price', 'gdp', 'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'infant_mortality',
       'largest_city', 'life_expectancy', 'maternal_mortality_ratio',
       'minimum_wage', 'official_language', 'out_of_pocket_health_expenditure',
       'physicians_per_thousand', 'population',
       'population_labor_force_participation', 'tax_revenue', 'total_tax_rate',
       'unemployment_rate', 'urban_population', 'latitude', 'longitude',
       'continent'],
      dtype='str')

In [6]:
len(df.columns[df.isnull().any()])

34

In [8]:
df.shape

(195, 36)

In [9]:
df.isnull().sum()

country                                   0
density                                   0
abbreviation                              7
agricultural_land                         7
land_area                                30
armed_forces_size                        29
birth_rate                                6
calling_code                              1
capital/major_city                        3
co2-emissions                            12
cpi                                      20
cpi_change                               16
currency-code                            15
fertility_rate                            7
forested_area                             7
gasoline_price                           20
gdp                                       2
gross_primary_education_enrollment        7
gross_tertiary_education_enrollment      12
infant_mortality                          6
largest_city                              6
life_expectancy                           8
maternal_mortality_ratio                 14
minimum_wage                             45
official_language                         5
out_of_pocket_health_expenditure          7
physicians_per_thousand                   7
population                              156
population_labor_force_participation     19
tax_revenue                              26
total_tax_rate                           12
unemployment_rate                        19
urban_population                        150
latitude                                  1
longitude                                 1
continent                                 1
dtype: int64

 El método óptimo depende del tipo de dato (numérico, categórico) y contexto: por ejemplo, media o mediana para numéricos, moda para categóricos, o técnicas avanzadas como KNN

In [13]:
columnas_numericas = df.select_dtypes(include=["number"])

In [15]:
columnas_numericas.columns

Index(['density', 'agricultural_land', 'land_area', 'armed_forces_size',
       'birth_rate', 'calling_code', 'co2-emissions', 'cpi', 'cpi_change',
       'fertility_rate', 'forested_area', 'gasoline_price', 'gdp',
       'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population', 'population_labor_force_participation', 'tax_revenue',
       'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
       'longitude'],
      dtype='str')

In [20]:
# Para una columna numérica
imputer = SimpleImputer(strategy='calling_code')
df['calling_code'] = imputer.fit_transform(df[['calling_code']])

InvalidParameterError: The 'strategy' parameter of SimpleImputer must be a str among {'constant', 'most_frequent', 'mean', 'median'} or a callable. Got 'calling_code' instead.

In [23]:
df.select_dtypes(include = 'number')

,density,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,co2-emissions,cpi,cpi_change,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,life_expectancy,maternal_mortality_ratio,minimum_wage,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude
0,60.0,58.1,652.2300,323.0,32.49,93.0,8.672,149.900,2.30,4.47,2.1,0.70,1.910135e+10,104.0,9.70,47.9,64.50,638.0,0.430,78.4,0.28,504.5466,48.90,9.30,71.40,11.120,574.7288,33.939110,67.709953
1,105.0,43.1,28.7480,9.0,11.78,355.0,4.536,119.050,1.40,1.62,28.1,1.36,1.527808e+10,107.0,55.00,7.8,78.50,15.0,1.120,56.9,1.20,504.5466,55.70,18.60,36.60,12.330,527.6378,41.153332,20.168331
2,18.0,17.4,145.1964,317.0,24.28,213.0,150.006,151.360,2.00,3.02,0.8,0.28,1.699882e+11,109.9,51.40,20.1,76.70,112.0,0.950,28.1,1.72,546.9690,41.20,37.20,66.10,11.700,672.6548,28.033886,1.659626
3,164.0,40.0,468.0000,10.8,7.20,376.0,469.000,169.706,6.82,1.27,34.0,1.51,3.154058e+09,106.4,9.82,2.7,63.34,436.8,6.630,36.4,3.33,77.1420,70.06,16.54,34.84,8.058,67.8730,42.506285,1.521801
4,26.0,47.5,170.1552,117.0,40.73,244.0,34.693,261.730,17.10,5.52,46.3,0.97,9.463542e+10,113.5,9.30,51.6,60.80,241.0,0.710,33.4,0.21,546.9690,77.50,9.20,49.10,6.890,672.6548,-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,32.0,24.5,912.0500,343.0,17.88,58.0,164.175,257.272,254.90,2.27,52.7,0.00,4.823593e+11,97.2,79.30,21.4,72.10,125.0,0.010,45.8,1.92,546.9690,59.70,13.68,73.30,8.800,700.0132,6.423750,-66.589730
191,314.0,39.3,331.2100,522.0,16.75,84.0,192.668,163.520,2.80,2.05,48.1,0.80,2.619212e+11,110.6,28.50,16.5,75.30,43.0,0.730,43.5,0.82,546.9690,77.40,19.10,37.60,2.010,672.6548,14.058324,108.277199
192,56.0,44.6,527.9680,40.0,30.45,967.0,10.609,157.580,8.10,3.79,1.0,0.92,2.691440e+10,93.6,10.20,42.9,66.10,164.0,1.046,81.0,0.31,504.5466,38.00,18.12,26.60,12.910,654.7376,15.552727,48.516388
193,25.0,32.1,752.6180,16.0,36.19,260.0,5.141,212.310,9.20,4.63,65.2,1.40,2.306472e+10,98.7,4.10,40.4,63.50,213.0,0.240,27.5,1.19,504.5466,74.60,16.20,15.60,11.430,654.7376,-13.133897,27.849332
194,38.0,41.9,390.7570,51.0,30.68,263.0,10.983,105.510,0.90,3.62,35.5,1.34,2.144076e+10,109.9,10.00,33.9,61.20,458.0,0.486,25.8,0.21,504.5466,83.10,20.70,31.60,4.950,574.7288,-19.015438,29.154857

In [21]:
#Selección de Método de Imputación: Discute en tu compañera cuál sería la mejor estrategia para manejar los valores nulos en cada una de las columnas identificadas en el paso anterior.
# Para varias columnas numéricas

In [22]:
df.head(5)

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.2300,323.0,32.49,93.0,Kabul,8.672,149.900,2.30,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.70,47.9,Kabul,64.50,638.0,0.43,Pashto,78.4,0.28,504.5466,48.90,9.30,71.40,11.120,574.7288,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.7480,9.0,11.78,355.0,Tirana,4.536,119.050,1.40,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.00,7.8,Tirana,78.50,15.0,1.12,Albanian,56.9,1.20,504.5466,55.70,18.60,36.60,12.330,527.6378,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,145.1964,317.0,24.28,213.0,Algiers,150.006,151.360,2.00,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.40,20.1,Algiers,76.70,112.0,0.95,Arabic,28.1,1.72,546.9690,41.20,37.20,66.10,11.700,672.6548,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.0000,10.8,7.20,376.0,Andorra la Vella,469.000,169.706,6.82,EUR,1.27,34.0,1.51,3.154058e+09,106.4,9.82,2.7,Andorra la Vella,63.34,436.8,6.63,Catalan,36.4,3.33,77.1420,70.06,16.54,34.84,8.058,67.8730,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,170.1552,117.0,40.73,244.0,Luanda,34.693,261.730,17.10,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.30,51.6,Luanda,60.80,241.0,0.71,Portuguese,33.4,0.21,546.9690,77.50,9.20,49.10,6.890,672.6548,-11.202692,17.873887,Africa

In [25]:
#Imputación de Valores Nulos: Implementa el método de imputación seleccionado en el paso 2 para llenar los valores nulos en las columnas.
columnas_num = ['density', 'agricultural_land', 'land_area', 'armed_forces_size',
       'birth_rate', 'calling_code', 'co2-emissions', 'cpi', 'cpi_change',
       'fertility_rate', 'forested_area', 'gasoline_price', 'gdp',
       'gross_primary_education_enrollment',
       'gross_tertiary_education_enrollment', 'infant_mortality',
       'life_expectancy', 'maternal_mortality_ratio', 'minimum_wage',
       'out_of_pocket_health_expenditure', 'physicians_per_thousand',
       'population', 'population_labor_force_participation', 'tax_revenue',
       'total_tax_rate', 'unemployment_rate', 'urban_population', 'latitude',
       'longitude']  # Reemplaza con tus columnas
imputer_knn = KNNImputer(n_neighbors=5)
df[columnas_num] = imputer_knn.fit_transform(df[columnas_num])

df.head()

,country,density,abbreviation,agricultural_land,land_area,armed_forces_size,birth_rate,calling_code,capital/major_city,co2-emissions,cpi,cpi_change,currency-code,fertility_rate,forested_area,gasoline_price,gdp,gross_primary_education_enrollment,gross_tertiary_education_enrollment,infant_mortality,largest_city,life_expectancy,maternal_mortality_ratio,minimum_wage,official_language,out_of_pocket_health_expenditure,physicians_per_thousand,population,population_labor_force_participation,tax_revenue,total_tax_rate,unemployment_rate,urban_population,latitude,longitude,continent
0,Afghanistan,60.0,AF,58.1,652.2300,323.0,32.49,93.0,Kabul,8.672,149.900,2.30,AFN,4.47,2.1,0.70,1.910135e+10,104.0,9.70,47.9,Kabul,64.50,638.0,0.43,Pashto,78.4,0.28,504.5466,48.90,9.30,71.40,11.120,574.7288,33.939110,67.709953,Asia
1,Albania,105.0,AL,43.1,28.7480,9.0,11.78,355.0,Tirana,4.536,119.050,1.40,ALL,1.62,28.1,1.36,1.527808e+10,107.0,55.00,7.8,Tirana,78.50,15.0,1.12,Albanian,56.9,1.20,504.5466,55.70,18.60,36.60,12.330,527.6378,41.153332,20.168331,Europe
2,Algeria,18.0,DZ,17.4,145.1964,317.0,24.28,213.0,Algiers,150.006,151.360,2.00,DZD,3.02,0.8,0.28,1.699882e+11,109.9,51.40,20.1,Algiers,76.70,112.0,0.95,Arabic,28.1,1.72,546.9690,41.20,37.20,66.10,11.700,672.6548,28.033886,1.659626,Africa
3,Andorra,164.0,AD,40.0,468.0000,10.8,7.20,376.0,Andorra la Vella,469.000,169.706,6.82,EUR,1.27,34.0,1.51,3.154058e+09,106.4,9.82,2.7,Andorra la Vella,63.34,436.8,6.63,Catalan,36.4,3.33,77.1420,70.06,16.54,34.84,8.058,67.8730,42.506285,1.521801,Europe
4,Angola,26.0,AO,47.5,170.1552,117.0,40.73,244.0,Luanda,34.693,261.730,17.10,AOA,5.52,46.3,0.97,9.463542e+10,113.5,9.30,51.6,Luanda,60.80,241.0,0.71,Portuguese,33.4,0.21,546.9690,77.50,9.20,49.10,6.890,672.6548,-11.202692,17.873887,Africa

In [ ]:
#Informe: Agregue al final de un jupyter una explicación breve que describa las columnas que tenían valores nulos, cómo decidir imputarlos y cualquier observación adicional que considere importante sobre el proceso de limpieza de datos.

## Informe de Limpieza de Datos - Tratamiento de Valores Nulos

### Columnas con Valores Nulos Identificadas
El análisis inicial identificó **27 columnas numéricas** con valores faltantes en el dataset `world_data_full_apply.csv`. Las principales fueron: densidad, tierra agrícola, emisiones de CO2, PIB, esperanza de vida, tasa de mortalidad infantil, entre otras.

### Método de Imputación Seleccionado
Se utilizó el método **KNN Imputer (K-Nearest Neighbors)** con 5 vecinos más cercanos para imputar los valores nulos. Esta técnica fue elegida por:
- **Ventaja**: Captura relaciones complejas entre variables, utilizando similitud entre países basada en características existentes.
- **Contexto**: Apropiado para datos geográficos/socioeconómicos donde países similares tienden a valores similares.
- **Robustez**: Mejor que media/mediana para datasets heterogéneos con múltiples dimensiones.

### Observaciones Importantes del Proceso

1. **Preservación de Estructura**: La imputación mantiene la distribución y correlaciones entre variables mejor que métodos simples.

2. **Validación**: Después de la imputación, `df.isnull().sum()` confirma 0 valores faltantes en todas las columnas tratadas.

3. **Limitaciones**: El KNN asume que valores similares se encuentran cercanos en el espacio de características. En casos de valores extremos aislados, podría suavizar demasiado las imputaciones.

4. **Siguientes Pasos**: Se recomienda explorar visualizaciones (boxplots, histogramas) para validar que las distribuciones imputadas son coherentes con los datos originales y realizar análisis de sensibilidad si el modelo es crítico.

 # METODOS:
 - Numérico (ej. edad, ingresos): Media (si distribución normal) o mediana (si sesgada).
- Categórico (ej. género, país): Moda (valor más frecuente).
- Avanzado: KNNImputer para patrones complejos o IterativeImputer para relaciones entre variables.